// <auto-generated />
namespace AprendendoEF.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Refazer_Foreign_Key_Venda_ItemVenda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refazer_Foreign_Key_Venda_ItemVenda));
        
        string IMigrationMetadata.Id
        {
            get { return "201705121253315_Refazer_Foreign_Key_Venda_ItemVenda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
