// <auto-generated />
namespace AprendendoEF.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criar_Item_Item_venda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criar_Item_Item_venda));
        
        string IMigrationMetadata.Id
        {
            get { return "201704281648426_Criar_Item_Item_venda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
