// <auto-generated />
namespace AprendendoEF.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criando_a_ForeignKey_Produto_x_Grupo_produto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criando_a_ForeignKey_Produto_x_Grupo_produto));
        
        string IMigrationMetadata.Id
        {
            get { return "201704241327352_Criando_a_ForeignKey_Produto_x_Grupo_produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
