// <auto-generated />
namespace AprendendoEF.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criacao_Grupo_Produtos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criacao_Grupo_Produtos));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111635418_Criacao_Grupo_Produtos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
